### ISSUE TITLE
Project does not build on raspberry pi

### ISSUE THREAD

**Issue by dasl-** [lincheney/rl_custom_isearch#3]
This is the change that was required to make it build on the raspberry pi: https://github.com/dasl-/rl_custom_isearch/commit/72d818c662082a23043b2d7e2c15d78f15ce0bd7

Not sure why... I wonder if it's related to the fact that the raspberry pi OS is 32 bits?

After making this change, everything works beautifully.

**Comment by lincheney** [comment]
Sorry for taking so long
Seems to be similar issue to this? https://github.com/Yubico/yubihsmrs/issues/9
I've pushed https://github.com/lincheney/rl_custom_isearch/commit/e8ba9b95a00993ea818151225f9d7ea538ef609c but I don't have a pi to test it on

**Comment by dasl-** [comment]
Now I have to apologize for taking so long :)

I have tested your fix on a raspberry pi and it works! thank you!
